### ISSUE TITLE
Enabling the use of the line input 2 in the driver software?

### ISSUE THREAD

**Issue by RinusW** [waveshare/WM8960-Audio-HAT#2]
Hi,
I was wondering of it would be possible to enable the use of the line input 2 (LINPUT2, RINPUT2) in the driver software? I could imagine that you then have 2 subdevices 0 and 1 in such a way that 
sudo arecord -D hw1,0 is using the mics, and sudo arecord hw1,1 is using the line input. Or the driver implements 2 devices: 1,0 is the mics, and 2,0 is the line input.

Although I am able to program in C, I could not find a way to do this in your code. Could it be done? An maybe someone already did it? 
This could make your Audio_HAT a much more attractive replacement for the discontinued Wolfson/Cirrus Logic Audio Card. 

Regards, Rinus

**Comment by hnwangkg-ezio** [comment]
you can use system("sudo arecord -D hw1,0") in c
