### ISSUE TITLE
an error occurs during installation...

### ISSUE THREAD

**Issue by DmitrySV77** [waveshare/WM8960-Audio-HAT#3]
Building module:
cleaning build area.....
make -j1 KERNELRELEASE=4.19.42+ -C /lib/modules/4.19.42+/build M=/var/lib/dkms/wm8960-soundcard/1.0/build..........(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.42+ (armv6l)
Consult /var/lib/dkms/wm8960-soundcard/1.0/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area.....
make -j1 KERNELRELEASE=4.19.42-v7+ -C /lib/modules/4.19.42-v7+/build M=/var/lib/dkms/wm8960-soundcard/1.0/build........(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.42-v7+ (armv6l)
Consult /var/lib/dkms/wm8960-soundcard/1.0/build/make.log for more information.
Created symlink /etc/systemd/system/sysinit.target.wants/wm8960-soundcard.service → /lib/systemd/system/wm8960-soundcard.service.

**Comment by DmitrySV77** [comment]
pi@raspberrypi:~/WM8960-Audio-HAT $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by ed74** [comment]
I also met this problem.

Attached /var/lib/dkms/wm8960-soundcard/1.0/build/make.log
[make.log](https://github.com/waveshare/WM8960-Audio-HAT/files/3194986/make.log)

Environment:
Raspberry Pi Zero W
Raspbian: April 2019

**Comment by hnwangkg-ezio** [comment]
This may be caused by the latest system of the Raspberry Pi.

**Comment by DmitrySV77** [comment]
OK, what image raspbian do I need to put in order for the wm8960 module to work?

**Comment by hnwangkg-ezio** [comment]
just for now:2018-11-13-raspbian-stretch-lite

**Comment by hnwangkg-ezio** [comment]
https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-11-15/

**Comment by ed74** [comment]
@hnwangkg-ezio 
> just for now:2018-11-13-raspbian-stretch-lite
> https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-11-15/

it doesn't work
the kernel was updated to 4.19.42-v7+ during install (install.sh)

**Comment by vaghawan** [comment]
HI any update on this? Facing the same issue with my PI 3B with rasbian strech "Raspbian GNU/Linux 9 (stretch)".

**Comment by 819428900** [comment]
use this https://github.com/respeaker/seeed-voicecard

**Comment by vaghawan** [comment]
Did that, it installs fine and the the device is shown, however the device doesn't work, neither the arecord, nor the aplay.

**Comment by 819428900** [comment]
The 2019-04-08-raspbian-stretch-lite I installed with the zero w, works fine.

**Comment by vaghawan** [comment]
HI @819428900 it worked. But I had to reboot Pi multiple times. Thank you for the help.

**Comment by DmitrySV77** [comment]
you did update and upgrade?

**Comment by vaghawan** [comment]
No, I didn't. At least not the upgrade.

**Comment by DmitrySV77** [comment]
but without it, get does not work ....

**Comment by DmitrySV77** [comment]
Sorry. git

**Comment by vaghawan** [comment]
I didn't fully understand you, I didn't use this repo, I rather used the repo of seeed-voicecard. Their installation worked after few boots. I used the Rasbian Stretch "2018-11-13-raspbian-stretch-full.img" downloaded from the rasbian.org in my PI 3B+.

**Comment by DmitrySV77** [comment]
git clone https://github.com/respeaker/seeed-voicecard
Command not found

**Comment by 819428900** [comment]
sudo apt-get install git

**Comment by DmitrySV77** [comment]
thank!  a sound has appeared.  Now I am trying to finish the pi-radio project ..... I installed the program, but there is no sound there ....

**Comment by hnwangkg-ezio** [comment]
now,fix it

**Comment by ed74** [comment]
@hnwangkg-ezio 
It works! Thanks!

I tried to clean install 2019-04-08-raspbian-stretch-lite.img on Pi Zero W.
Driver build under 4.19.42+ and 4.19.42-v7+ kernel.

Double check device list
```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: wm8960soundcard [wm8960-soundcard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: wm8960soundcard [wm8960-soundcard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by hnwangkg-ezio** [comment]
This seems to be working.

**Comment by LiJu09** [comment]
> @hnwangkg-ezio
> It works! Thanks!
> 
> I tried to clean install 2019-04-08-raspbian-stretch-lite.img on Pi Zero W.
> Driver build under 4.19.42+ and 4.19.42-v7+ kernel.
> 
> Double check device list
> 
> ```
> $ aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: wm8960soundcard [wm8960-soundcard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
>   Subdevices: 7/7
>   Subdevice #0: subdevice #0
>   Subdevice #1: subdevice #1
>   Subdevice #2: subdevice #2
>   Subdevice #3: subdevice #3
>   Subdevice #4: subdevice #4
>   Subdevice #5: subdevice #5
>   Subdevice #6: subdevice #6
> card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> 
> $ arecord -l
> **** List of CAPTURE Hardware Devices ****
> card 0: wm8960soundcard [wm8960-soundcard], device 0: bcm2835-i2s-wm8960-hifi wm8960-hifi-0 []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> ```

I try the same
Not work for me

**Comment by iTommix** [comment]
For newer Kernel (in my case 4.19.66-v7+) you have to link the new Kernel-Sourcen to the installer expected 4.14.98-v7+ (i dont know why the installer expect these):

`sudo ln -s /lib/modules/4.19.66-v7+ /lib/modules/4.14.98-v7+`
or
`sudo ln -s /lib/modules/$(uname -r) /lib/modules/4.14.98-v7+`

then execute the install.sh

This worked for me.

**Comment by Daveolw** [comment]
Hi,
Facing the same issue with my PI 3B with rasbian strech "Raspbian GNU/Linux 9 (stretch)
Purchased WM8960 sound card but cannot get it working,   Error! Bad return status for module build on kernel: 4.19.66-v7+ (armv7l)
End of Log file shown.
[log.txt](https://github.com/waveshare/WM8960-Audio-HAT/files/5286728/log.txt)

Tried above suggestions but cannot git it to install.
Any ideas?

**Comment by Daveolw** [comment]
Did a complete reinstall of Raspbian GNU/Linux 9 (stretch), WM8960 install, even more errors, How to solve this?
File of setup and log of errors.
[newinstall.txt](https://github.com/waveshare/WM8960-Audio-HAT/files/5287085/newinstall.txt)
