### ISSUE TITLE
The driver does not seem to work on Raspberry Pi 5

### ISSUE THREAD

**Issue by ubopod** [waveshare/WM8960-Audio-HAT#51]
Installing the driver makes OS crash after reboot.  Is there going to be a driver update for Raspberry Pi 5?

**Comment by ubopod** [comment]
I opened a ticket and staff responded with the following fix that I tested and works on Pi 5 and Pi 4:

`sudo bash install_wm8960.sh`

https://github.com/ubopod/ubo-sdk/blob/main/system/setup/install_wm8960.sh

**Comment by cnyanhao** [comment]
Hi,

What did you do after failing the old method and before trying the new install_wm8960.sh? Do you uninstall the driver first? Do you set arm_64bit=0 in /boot/config.txt?

Thank you.

**Comment by victrome** [comment]
The url provided doesn't work anymore. I found a install_wm8960.sh here https://github.com/bobrathbone/piradio6/blob/master/install_wm8960.sh

Somehow after a few reboots it worked... I think I was trying to restart the WM8960 service to check if it was running fine and that was the mistake. The service can only be started on boot
